### ISSUE TITLE
The way of defining colors in highlight (with variables)

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5-highlight#11]
Currently, we are defining colors of pen/markers in editor.config:

``` js
{ 
   model: 'yellowMarker', 
   class: 'marker-yellow', 
   title: 'Yellow marker', 
   color: '#fdfd77', 
   type: 'marker' 
}
```

In fact this color property makes only **marker or pen** icon changed and user needs to copy this hex/rgb/whatever value to CSS styles to make selection background/color works. 
We can see it in Manual Tests ( [ckeditor5-highlight/tests/manual/highlight-buttons.html#L1-L27](https://github.com/ckeditor/ckeditor5-highlight/blob/master/tests/manual/highlight-buttons.html#L1-L27) ).

## Idea

We can use the power of CSS variables and use them in highlight options.

```js
{ 
   model: 'yellowMarker', 
   class: 'marker-yellow', 
   title: 'Yellow marker', 
   color: 'var(--marker-yellow)', // or var(--ck-marker-yellow)?
   type: 'marker' 
}
```

Then in [ckeditor5-highlight/theme/highlight.css](https://github.com/ckeditor/ckeditor5-highlight/blob/master/theme/highlight.css) we can define them:

```css
:root {
     --ck-marker-yellow: #fdfd77;
     --ck-marker-green: #63f963;
     --ck-pen-blue: #72cdfd;
}
```
and add clasess for handling selection background/color
```css
.marker-yellow { 
     background-color: var(--ck-marker-yellow)
}
```
We can do it via @mixin too:

```css
@define-mixin marker-background $color {
     .ck-marker-$color { 
          background-color: var(--ck-marker-$color);
     }
}

/* usage */ 
@mixin marker-background-yellow;
@mixin marker-background-blue;
@mixin marker-background-green;
```

## Pros
- one variable and no need to define colors twice
## Cons
- what if someone what to change lightness of yellow in icon but not in selection?

cc @jodator @oleq
